// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiGdybDZgUO7tXmEKQ8w3qzSCZcjE9Abw',
    appId: '1:848918851283:web:f1ae2284b69bb4bfb06e26',
    messagingSenderId: '848918851283',
    projectId: 'ecommerceapp-7499c',
    authDomain: 'ecommerceapp-7499c.firebaseapp.com',
    storageBucket: 'ecommerceapp-7499c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGIecE6cUCPQdNsKEtdn-IjNlHe4d8pkU',
    appId: '1:848918851283:android:98ec6ac4ed451355b06e26',
    messagingSenderId: '848918851283',
    projectId: 'ecommerceapp-7499c',
    storageBucket: 'ecommerceapp-7499c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVfoUXcq6vFdYr8po4jhqEHorjkXy7rfY',
    appId: '1:848918851283:ios:d8304f0a806f9d0db06e26',
    messagingSenderId: '848918851283',
    projectId: 'ecommerceapp-7499c',
    storageBucket: 'ecommerceapp-7499c.appspot.com',
    androidClientId: '848918851283-9rpkpagd5akboueveg4kjadugeg2rm9a.apps.googleusercontent.com',
    iosClientId: '848918851283-dmn29jp7apni56ho9vl20d77uost2d2p.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

}